apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search-service
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - image: denitiawan/argocd-springboot3-service:latest
          name: search-service
        env:
          - name: APP_PORT
            value: 80
          - name: APP_NAME
            value: SEARCH-SERVICE     